### ISSUE TITLE
 ERROR: Cannot read file seqalign.fasta

### ISSUE THREAD

**Issue by vinitamehlawat** [MountainMan12/SARS_phylo#2]
Hi there!

I am trying phylodynamics of SARSCoV2 using your pipeline. I am having the GISAID data for CoV2 and one Reference genome with which I want to do alignment using MAFFT and want to generate a phylogenetic tree, But I am getting following error: **Reading alignment file seqalign.fasta ... ERROR: Cannot read file seqalign.fasta
opening the tree file
javax.swing.UIManager$LookAndFeelInfo[Metal javax.swing.plaf.metal.MetalLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[Nimbus javax.swing.plaf.nimbus.NimbusLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[CDE/Motif com.sun.java.swing.plaf.motif.MotifLookAndFeel]
javax.swing.UIManager$LookAndFeelInfo[GTK+ com.sun.java.swing.plaf.gtk.GTKLookAndFeel]
Exception while loading the ApplicationAdapter:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jam.mac.Utils.registerDesktopApplication(Unknown Source)
	at jam.framework.MultiDocApplication.initialize(Unknown Source)
	at figtree.application.FigTreeApplication.main(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: The APP_ABOUT action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
	at java.desktop/java.awt.Desktop.setAboutHandler(Desktop.java:696)
	at jam.java9only.ApplicationAdapter.registerApplication(Unknown Source)
	... 7 more**
I am not sure how to put the reference genome  and genome files from GISAID in your code. Please help me to solve this issue

**Comment by liamxg** [comment]
Dear @vinitamehlawat ,

Could I. know what is your command?

Thanks.

Best,
Liam
